server:
  port: 5001

spring:
  application:
    name: account.query
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/bankAccount?createDatabaseIfNotExist=true
    username: cqrs
    password: cqrs@123
  kafka:
    listener:
      ack-mode: MANUAL_IMMEDIATE
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: bankAccConsumer
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: '*'